# SPDX-License-Identifier: GPL-2.0

icc-osm-l3-objs				:= osm-l3.o
qnoc-sdm845-objs			:= sdm845.o

obj-$(CONFIG_INTERCONNECT_QCOM_OSM_L3) += icc-osm-l3.o
obj-$(CONFIG_INTERCONNECT_QCOM_SDM845) += qnoc-sdm845.o
